# Generated by Django 5.0.3 on 2024-03-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=80, unique=True)),
                ('class_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('class_term', models.CharField(max_length=6)),
                ('class_year', models.PositiveSmallIntegerField()),
                ('class_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(max_length=50)),
                ('assignment_weight', models.DecimalField(decimal_places=3, max_digits=3)),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.class')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.assignment_weights')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.class')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
